version: '3.8'

services:
  postgres_certification:
    container_name: AccessWise
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=AccessWise